### ISSUE TITLE
Migrate nodes/GatewayServer to serverless

### ISSUE THREAD

**Issue by pileks** [polywrap/wrappers-io#14]
Exclude `/add`

- [ ] GET `/`
- [ ] POST `/api/v0/add`
- [ ] GET `/pins`
- [ ] GET `/api/v0/resolve`
- [ ] POST `/api/v0/get`
- [ ] GET `/api/v0/cat`
- [ ] GET `/pin/ls`
- [ ] GET `/view/ipfs/:path(*)`

Will not implement:
- [ ] ~~GET `/status/:cid`~~ Not needed
- [ ] ~~GET `/add`~~ Legacy
